name: Build glues macOS

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main
      - develop
jobs:
  check-environmet:
    name: Check environment
    runs-on: macos-14
    steps:
      - name: Check MacOS XCode version
        run: |
          echo "macOS version:"
          sw_vers

  build:
    name: Build glues
    runs-on: macos-14
    needs: check-environmet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Debug build
        run: |
          cmake -S . -B build/Debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build/Debug

      - name: Release build
        run: |
          cmake -S . -B build/Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build/Release

      - name: Zip
        run: |
          TAG=${{ github.ref_name }}
          mkdir "glues_${TAG}"
          mv ./out/glues "glues_${TAG}/glues" 
          zip -r "glues_${TAG}.zip" "glues_${TAG}"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          name: "glues library for macOS ${{ github.ref_name }}"
          body: |
            🔨 Built from glues commit [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          artifacts: |
            glues_${{ github.ref_name }}.zip